### ISSUE TITLE
Montar página do formulário

### ISSUE THREAD

**Issue by GusChenn** [nmcardoso/engsoft#15]
Juntar componentes para montar a página do formulário

**Comment by GusChenn** [comment]
Tive uns problemas pra rodar o projeto depois das alterações que rolaram, então pra evitar perder muito tempo, criei o branch 'gambeta' onde eu fiz o react renderizar só a página que eu to editando. Já comecei a página do formulário, pretendo acabar hj

**Comment by nmcardoso** [comment]
depois de dar `git pull` os scripts pararam de funcionar no `npm start`?

**Comment by GusChenn** [comment]
Upei a página do jeito que está. Só falta fazer as funções de verificação (não pode marcar as duas doses de uma vez, não pode deixar uns campos em branco, verificar cpf e blablabla) e integrar com o bd. Também tenho que resolver o dropdown que ta foda fazer ele funcionar KKKKKKKK

**Comment by nmcardoso** [comment]
dá uma olhada de como eu fiz o dropdown na página de registro

**Comment by GusChenn** [comment]
Fazer o botão de 'send'

**Comment by GusChenn** [comment]
Fazer também os novos campos descritos no novas_colunas.txt

**Comment by GusChenn** [comment]
Copiei as alterações de 'gambeta' pro 'main', mas não consegui rodar por causa do problema no BD.

**Comment by nmcardoso** [comment]
se você rodar `npm run db:sync` dentro da pasta `/api` no **linux** ele sincroniza o novo db pra você. (pelo menos pra mim funciona)

senão você pode tentar sincronizar manualmente o arquivo `database-data.psql` pelo pgadmin

**Comment by GusChenn** [comment]
Rodei o npm run db:sync no linux, deu esse erro:

> ***@***.*** db:sync /home/guschen/Documents/engsoft/api
> NODE_ENV=dev node utils/sync_db.js

Executing (default): SELECT 1+1 AS result
Executing (default): DROP TABLE IF EXISTS "usuario" CASCADE;
Database connected
Executing (default): DROP TABLE IF EXISTS "unidade_saude" CASCADE;
Executing (default): DROP TABLE IF EXISTS "login" CASCADE;
Executing (default): DROP TABLE IF EXISTS "formulario" CASCADE;
Executing (default): DROP TABLE IF EXISTS "feedback" CASCADE;
Executing (default): DROP TABLE IF EXISTS "feedback" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "feedback" ("id"  SERIAL ,
"cpf_usuario" VARCHAR(255), "mensagem" VARCHAR(255), "createdAt" TIMESTAMP
WITH TIME ZONE, "u
pdatedAt" TIMESTAMP WITH TIME ZONE, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary,
ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as
column_indexes, array_a
gg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition
FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid =
ix.indrelid AND i.oid
= ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname =
'feedback' GROUP BY i.relname, ix.indexrelid, ix.indisprimary,
ix.indisunique, ix.indkey ORD
ER BY i.relname;
Executing (default): DROP TABLE IF EXISTS "formulario" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "formulario" ("id"  SERIAL
, "id_unidade_saude" INTEGER, "cpf" VARCHAR(255), "telefone" VARCHAR(255),
"nome" VARCHAR(255
), "data_nascimento" TIMESTAMP WITH TIME ZONE, "laboratorio" VARCHAR(255),
"lote" INTEGER, "data_vacinacao" TIMESTAMP WITH TIME ZONE, "dose" INTEGER,
"createdAt" TIMEST
AMP WITH TIME ZONE, "updatedAt" TIMESTAMP WITH TIME ZONE, PRIMARY KEY
("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary,
ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as
column_indexes, array_a
gg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition
FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid =
ix.indrelid AND i.oid
= ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname =
'formulario' GROUP BY i.relname, ix.indexrelid, ix.indisprimary,
ix.indisunique, ix.indkey O
RDER BY i.relname;
Executing (default): DROP TABLE IF EXISTS "login" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "login" ("id"  SERIAL ,
"username" VARCHAR(255) NOT NULL, "password" VARCHAR(255) NOT NULL, "nome"
VARCHAR(255) NOT NULL
, "cpf" VARCHAR(255) NOT NULL, "id_unidade_saude" INTEGER NOT NULL,
"createdAt" TIMESTAMP WITH TIME ZONE, "updatedAt" TIMESTAMP WITH TIME ZONE,
PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary,
ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as
column_indexes, array_a
gg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition
FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid =
ix.indrelid AND i.oid
= ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname =
'login' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique,
ix.indkey ORDER
BY i.relname;
Executing (default): DROP TABLE IF EXISTS "unidade_saude" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "unidade_saude" ("id"
  SERIAL , "nome" VARCHAR(255), "endereco" VARCHAR(255), "cep"
VARCHAR(255), "createdAt" TIMESTAMP
WITH TIME ZONE, "updatedAt" TIMESTAMP WITH TIME ZONE, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary,
ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as
column_indexes, array_a
gg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition
FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid =
ix.indrelid AND i.oid
= ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname =
'unidade_saude' GROUP BY i.relname, ix.indexrelid, ix.indisprimary,
ix.indisunique, ix.indke
y ORDER BY i.relname;
Executing (default): DROP TABLE IF EXISTS "usuario" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "usuario" ("id"  SERIAL ,
"cpf" VARCHAR(255), "nome" VARCHAR(255), "username" VARCHAR(255),
"password" VARCHAR(255), "id
_saude" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE, "updatedAt"
TIMESTAMP WITH TIME ZONE, PRIMARY KEY ("id"));
Executing (default): SELECT i.relname AS name, ix.indisprimary AS primary,
ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as
column_indexes, array_a
gg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition
FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid =
ix.indrelid AND i.oid
= ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname =
'usuario' GROUP BY i.relname, ix.indexrelid, ix.indisprimary,
ix.indisunique, ix.indkey ORDE
R BY i.relname;


[
 'Feedback.js',
 'Formulario.js',
 'Login.js',
 'UnidadeSaude.js',
 'Usuario.js'
]



>> Banco Sincronizado com Sucesso
Executing (default): SELECT setval('feedback_id_seq', (SELECT MAX(id) FROM
"feedback"))
Executing (default): SELECT setval('formulario_id_seq', (SELECT MAX(id)
FROM "formulario"))
Executing (default): SELECT setval('login_id_seq', (SELECT MAX(id) FROM
"login"))
Executing (default): SELECT setval('unidadesaude_id_seq', (SELECT MAX(id)
FROM "unidadesaude"))
Executing (default): SELECT setval('usuario_id_seq', (SELECT MAX(id) FROM
"usuario"))
(node:22773) UnhandledPromiseRejectionWarning: SequelizeDatabaseError:
relation "unidadesaude" does not exist
   at Query.formatError
(/home/guschen/Documents/engsoft/api/node_modules/sequelize/lib/dialects/postgres/query.js:386:16)

   at Query.run
(/home/guschen/Documents/engsoft/api/node_modules/sequelize/lib/dialects/postgres/query.js:87:18)

   at processTicksAndRejections (internal/process/task_queues.js:95:5)
   at async
/home/guschen/Documents/engsoft/api/node_modules/sequelize/lib/sequelize.js:619:16

   at async /home/guschen/Documents/engsoft/api/utils/sync_db.js:9:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22773) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either by throwing inside of an async function
without a catch block,
or by rejecting a promise which was not handled with .catch(). To terminate
the node process on unhandled promise rejection, use the CLI flag
`--unhandled-rejections=st
rict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode).
(rejection id: 1)
(node:22773) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, promise rejections that are not handled will
terminate the Node.j
s process with a non-zero exit code.



Em ter., 13 de jul. de 2021 às 23:27, Natanael ***@***.***>
escreveu:

**Comment by nmcardoso** [comment]
Chen, quando vc executa esse comando ele exibe várias linhas mesmo. Mas
veja que o banco de dados foi sincronizado como esperado. O único problema
foi no final que ele não conseguiu criar a sequência da unidade de saúde pq
o nome da tabela tem underscore. Eu já corrigi isso e não tem mais esse
erro. Mas o seu db local foi atualizado, a única coisa que daria errado
seria criar um novo registro no tabela unidade_saude, mas isso não acontece
pq o app não tem essa função. Tenta rodar o script de novo. Se na última
linha aparecer `banco sincronizado com sucesso` é pq deu tudo certo.

Em qua, 14 de jul de 2021 16:33, Gustavo Chen ***@***.***>
escreveu:

**Comment by GusChenn** [comment]
Boa, rodei o comando dnv. Apareceu que o banco foi sincronizado, mas deu
esse erro depois de uns SELECTs:

(node:11578) UnhandledPromiseRejectionWarning: SequelizeDatabaseError:
relation "unidadesaude" does not ex
ist
   at Query.formatError
(/home/guschen/Documents/engsoft/api/node_modules/sequelize/lib/dialects/postgres
/query.js:386:16)
   at Query.run
(/home/guschen/Documents/engsoft/api/node_modules/sequelize/lib/dialects/postgres/query.j
s:87:18)
   at processTicksAndRejections (internal/process/task_queues.js:95:5)
   at async
/home/guschen/Documents/engsoft/api/node_modules/sequelize/lib/sequelize.js:619:16

   at async /home/guschen/Documents/engsoft/api/utils/sync_db.js:9:5
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11578) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
This error originated either b
y throwing inside of an async function without a catch block, or by
rejecting a promise which was not hand
led with .catch(). To terminate the node process on unhandled promise
rejection, use the CLI flag `--unhan
dled-rejections=strict` (see
https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection
id
: 1)
(node:11578) [DEP0018] DeprecationWarning: Unhandled promise rejections are
deprecated. In the future, pro
mise rejections that are not handled will terminate the Node.js process
with a non-zero exit code.

Em qui., 15 de jul. de 2021 às 07:11, Natanael ***@***.***>
escreveu:
