### ISSUE TITLE
Gambeta de Atualização do PB

### ISSUE THREAD

**Issue by fabiotnaka** [nmcardoso/engsoft#19]
Faremos um fluxo de atualização automatizado do dashboard no Power BI, exportando um csv a partir de uma view que devolve exatamente os dados que serão utilizados para a visualização e colocaremos numa URL. A partir disso o Power BI consegue puxar esse dados via requisição HTTP.

**Comment by fabiotnaka** [comment]
@nmcardoso o banco de dados antigo lá no seu pgadmin foi excluido né? 

A forma de puxar os dados pro Power BI continua sendo o mesmo?

**Comment by nmcardoso** [comment]
continua o mesmo
