### ISSUE TITLE
[Contínuo] Integrar front ends prontos ao backend

### ISSUE THREAD

**Issue by GusChenn** [nmcardoso/engsoft#23]
Ir integrando conforme as páginas ficarem prontas

**Comment by GusChenn** [comment]
Upei o branch 'front' com a página do dash já com todos os campos, mas com as funções comentadas pra eu poder acessar a página. Vc vai reparar que tem a página não ta descendo, mas eu resolvo isso amanhã.

**Comment by GusChenn** [comment]
@nmcardoso to tendo problemas pra acessa as páginas de login e cadastro. Toda vez que tento acessar essas páginas (até pela URL) eu caio no dashboard direto. Deve ser por causa daquelas verificações que vc disse que implementou na última reunião. Tem como vc ajustar isso pra que ainda seja possível entrar nas páginas de cadastro e login?

**Comment by nmcardoso** [comment]
Quando vc faz login ele armazena seus dados no "banco de dados" do navegador. Pra acessar a página vc pode apagar os dados acessando o inspetor, clique na aba armazenamento, depois armazenamento local (ou localStorage) e apaga os registros que lá tiverem. Recarregar a página e o site não lembrará de sua sessão antiga. Outra forma de fazer isso é simplesmente acessando a URL por uma janela anônima.

**Comment by GusChenn** [comment]
Consegui aq, obrigado


Em seg., 19 de jul. de 2021 às 17:54, Natanael ***@***.***>
escreveu:
