### ISSUE TITLE
Implementar states - formulário

### ISSUE THREAD

**Issue by GusChenn** [nmcardoso/engsoft#25]
Implementar a captação dos states na página do formulário

**Comment by nmcardoso** [comment]
Eu já fiz a parte que tinha combinado de fazer do fórmulario (cep para baixo). Você conseguiu fazer algo? Eu implementei usando reducer ao invés de state, o motivo é que além dos campos serem dependentes entre si a atualização ainda é assincrona (pegar informações do cep no servidor). Não dava pra fazer com state pq só o reducer consegue sincronizar os estados entre os componentes com funções assincronas. Qualquer coisa me chame aqui. @GusChenn

**Comment by GusChenn** [comment]
Boa. Ainda não fiz isso, mas pretendo fazer ainda hoje. Estava fazendo o
botão de home e a página do usuário.

**Comment by GusChenn** [comment]
Implementei todos os states, mas ainda não entendi como cria as máscaras. Você fez isso em algum lugar do código? Consegue apontar pra mim? To real tendo dificuldade com isso. Eu entendi que o uso dos states é uma maneira de fazer com que os inputs do usuário 'entrem' no programa. Agora como eu faço pra manipular esses inputs e formatar eles do jeito que eu quiser? Eu teria que usar essas máscaras pra isso? E pra usar máscaras, eu teria que incluir um pacote adicional no projeto (react-imput-mask) ou é alguma coisa nativa do react?

**Comment by nmcardoso** [comment]
Tem várias questões aqui. Sim, o pacote `react-input-mask` pode ser usado, mas veja que ele não resolve todos os casos, veja que uma másca é simplesmente um padrão que se aplica a um campo. Exemplo: todo cpf tem o padrão ddd.ddd.ddd-dd, onde D é um dígito, a máscara não garante que o cep seja válido. 111.111.111-11 é uma máscara válida, pois tem o padrão especificado. Além disso, ainda é preciso implementar a validação. Então veja que a validação tem mais prioridade de implementação que a máscara, visto que será preciso dela de qualquer jeito. Em campos como nome, onde não há um padrão de caracteres definido, existem duas abordagens possíveis: (a) usar uma "mascara" (no sentido de previnir que o usuário digite algum caractere inválido - não sei se você já preencheu um formulário onde você digita um caractere e ele simplesmente não aparece, seria isso; a outra (b) seria validação, onde o usuário digita o caractere inválido mas aparece uma mensagem de erro abaixo - esta última foi a que eu usei nos campos que fiz).
Sobre a questão da manipulação das informações: uma vez que você tem o valor do campo como variável, você pode interagir com ela quando e como quiser. Existem dois momentos especiais onde isso pode acontecer: (1) quando o valor acaba de ser digitado e (2) quando os dados estão prestes a serem enviados para o servidor.
Exemplo do caso (1):
Imagine que você quer validar se o campo idade possui apenas dígitos
```javascript
...
onChange={(event) => {
  const idade = event.target.value
  const isDigit = /\d*/g.test(idade)
  if (!isDigit) {
    setErrors({'idade': 'campo idade não possui valor válido')
  }
  setIdade(idade)
}}
...
```
você poderia fazer a mesma lógica para manipular o dado de entrada e impedir que aparece um caractere não numérico no campo assim:
```javascript
...
onChange={(event) => {
  let idade = event.target.value
  idade = idade.replaceAll(/\D/g, '')
  setIdade(idade)
}}
...
```
veja que nesse segundo caso eu fiz uma "máscara", eu manipulei os dados antes de salvar usado uma expressão regular (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) que remove qualquer caractere não-digito.
Esses dois códigos dão exemplos dos casos (a) e (b) no momento (1). Você pode fazer da forma que achar mais fácil, mas uma sugestão é continuar a implementação que eu já tinha começado (a implementação ficaria mais "uniforme"). Para fazer isso, você precisaria mecher em apenas 3 partes:

(1) Adicione um o nome do campo no array fields (como se fosse um id)
https://github.com/nmcardoso/engsoft/blob/99c9d6e665904773c130bcf1a8967f3aef211389/client/src/Dashboard.js#L13-L22

(2) Adicione um campo na variável `validate` com o mesmo nome que você deu para o campo no passo anterior.
https://github.com/nmcardoso/engsoft/blob/99c9d6e665904773c130bcf1a8967f3aef211389/client/src/Dashboard.js#L63-L118
veja que cada chave é uma função que retorna uma string que é a mensagem de erro (caso não houver, o valor de `error` pode ser `null` ou `undefined`). Nessa função você implementa a validação de cada campo.

(3) No componente, você setaria os valores de `className`, `onChange` e `onBlur` (quando o usuário clica fora do campo) como neste exemplo. Você chamaria a função `handleFieldChange` com o nome do campo (o mesmo dos passos anteriores) e o valor do campo (que pode ser `e.target.value`, `e.target.checked`, etc...). E, logo abaixo do campo vocẽ adicionaria uma renderização condicional da mensagem de erro. A variável `touched` é uma flag geralmente usada para prevenir que o campo seja marcado como incorreto sem o usuário ter ao menos tocado. Você não precisa mudar o valor desta variavel manualmente
https://github.com/nmcardoso/engsoft/blob/99c9d6e665904773c130bcf1a8967f3aef211389/client/src/Dashboard.js#L516-L530

Esta é a explicação de como integrar o seu código ao meu. Eu vi os states que você fez. Eles estão certos. O único problema é que pra acrescentar validação na forma de states serão precisos mais 26 hooks (13 hooks para [errorCampo, setErrorCampo] e mais 13 para [touchedCampo, setTouchedCampo]), o que resultaria em 39 hooks, o que não é recomendado pelo react. Mas se o código que escrevi não tiver claro, faz do jeito que achar melhor.

**Comment by nmcardoso** [comment]
Outra coisa, se você testar as mensgaem de erro nos campos que eu implementei você vai ver que quase não dá pra ler a mensagem. A cor da mensagem tem pouco contraste com o background. Isso é uma coisa que tem que ser resolvida.

**Comment by GusChenn** [comment]
Vlw pela explicação! Eu não tinha entendido o que você tinha feito mesmo,
mas agora deu pra entender. Faço as alterações amanhã. Em relação à cor do
erro, eu mudei um pouco o visual do app no geral.

Mudei a tela inicial e a tela do formulário, colocando um fundo branco
atrás dos campos do formulário. As alterações foram subidas nesse meu
último commit, então dá uma olhada depois pra ver o que acha.

Em ter., 20 de jul. de 2021 às 21:35, Natanael ***@***.***>
escreveu:
