### ISSUE TITLE
Desenvolver Front End Loggin

### ISSUE THREAD

**Issue by GusChenn** [nmcardoso/engsoft#3]
Desenvolver o front end da página de loggin de nossa aplicação

**Comment by nmcardoso** [comment]
https://github.com/nmcardoso/splus-cloud-theme

**Comment by GusChenn** [comment]
Fiz umas alterações na aparência da página e coloquei o projeto modificado no branch 'front', mas não sei integrar com o backend. Quer marcar um horário para fazermos isso durante a semana? Ou se for coisa rápida, vc pode fazer essa integração e me explicar durante o lab essa semana também
