### ISSUE TITLE
Atualização da estrutura do banco de dados

### ISSUE THREAD

**Issue by GusChenn** [nmcardoso/engsoft#6]
Integrar SQL ao backend

**Comment by GusChenn** [comment]
[novas_colunas.txt](https://github.com/nmcardoso/engsoft/files/6812521/novas_colunas.txt)

**Comment by GusChenn** [comment]
Criar essas novas colunas e buscar por banco de localidades

**Comment by GusChenn** [comment]
[novas_colunasV2.txt](https://github.com/nmcardoso/engsoft/files/6812537/novas_colunasV2.txt)

**Comment by nmcardoso** [comment]
@fabiotnaka, tem duas coisas importantes (e simples) pra fazer no banco de dados

- Adicionar valor padrão para as colunas updatedAt and createdAt no postgres, o valor padrão deve ser a data atual. Acredito q não deve ser difícil fazer isso.
- Adicionar valor padrão para a coluna id, é possível fazer isso de duas formas. Durante a criação da tabela, colocando o tipo da coluna como `serial` ao invés de `inteiro`; ou via código (exemplo abaixo). Primeiro cria um objeto sequência (o nome deve ser `<nome_tabela>_<nome_coluna>_seq`) e depois altera a coluna para ter o valor default definido pela sequência. Só é preciso fazer isso se a coluna não tiver uma sequência já. Para saber se a coluna já tem uma sequência vc tenta inserir um registro sem especificar o id e veja se o id foi colocado automaticamente.

```sql
CREATE SEQUENCE test_table_id_seq 
    INCREMENT 1 
    MINVALUE 1
    CACHE 1; 

ALTER TABLE test_table ALTER COLUMN id SET DEFAULT nextval('test_table_id_seq'::regclass);
```
