### ISSUE TITLE
Alterar página de cadastro

### ISSUE THREAD

**Issue by GusChenn** [nmcardoso/engsoft#8]
Alterar informações exigidas na página de cadastro para se adequar ao planejamento.

**Comment by GusChenn** [comment]
Alterei o front pra receber todas as informações e criei estados para armazenar os resultados, mas não sei fazer com que o programa armazene todas essas informações no BD. Consegue me mostrar como faz isso amanha?

**Comment by nmcardoso** [comment]
sem problemas, você pode subir seu branch?

**Comment by GusChenn** [comment]
Upei o branch alteracoes-suicidas. Alterei varias coisas nos arquivos Forms.js, API.js, Login.js e sepa em outros lugares tbm. Se eu tiver cagado muita coisa, me avisa que eu clono o projeto dnv e mudo só o front.

**Comment by nmcardoso** [comment]
fiz um commit (9b19dd417) no seu branch, agora o código tá executando normalmente; vc pode dar um git pull no seu branch pra baixar as alterações

**Comment by GusChenn** [comment]
Fica como responsável dessa tarefa + fazer a consulta no BD para puxar as unidades de saúde enquanto eu foco no dash.
